apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: aaa_project_template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2017-07-15T13:11:19Z
    creationTimestamp: null
    generation: 2
    labels:
      app: jenkins
    name: jenkins
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker.io/library/jenkins:2.46.3
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/aaa/jenkins:2.46.3
      generation: 2
      importPolicy: {}
      name: 2.46.3
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: jenkins
    name: jenkins
  spec:
    replicas: 1
    selector:
      app: jenkins
      deploymentconfig: jenkins
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: jenkins
          deploymentconfig: jenkins
      spec:
        containers:
        - image: docker.io/library/jenkins@sha256:1a017bc762d8177347dbccbe258de842015114806110db060d91cff7e8a3264f
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
          - containerPort: 50000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: jenkins-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: jenkins:2.46.3
          namespace: aaa
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.name: jenkins-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: jenkins
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: image change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"jenkins","namespace":"aaa","selfLink":"/apis/apps.openshift.io/v1/namespaces/aaa/deploymentconfigs/jenkins","uid":"16ff7684-695f-11e7-b631-026048c65d66","resourceVersion":"3625","generation":3,"creationTimestamp":"2017-07-15T13:11:18Z","labels":{"app":"jenkins"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["jenkins"],"from":{"kind":"ImageStreamTag","namespace":"aaa","name":"jenkins:2.46.3"},"lastTriggeredImage":"docker.io/library/jenkins@sha256:1a017bc762d8177347dbccbe258de842015114806110db060d91cff7e8a3264f"}}],"replicas":1,"test":false,"selector":{"app":"jenkins","deploymentconfig":"jenkins"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"jenkins","deploymentconfig":"jenkins"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"volumes":[{"name":"jenkins-volume-1","emptyDir":{}}],"containers":[{"name":"jenkins","image":"docker.io/library/jenkins@sha256:1a017bc762d8177347dbccbe258de842015114806110db060d91cff7e8a3264f","ports":[{"containerPort":50000,"protocol":"TCP"},{"containerPort":8080,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"jenkins-volume-1","mountPath":"/var/jenkins_home"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":2,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"image change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"ImageStreamTag","namespace":"aaa","name":"jenkins:2.46.3"}}}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2017-07-15T13:11:18Z","lastTransitionTime":"2017-07-15T13:11:18Z","message":"Deployment config does not have minimum availability."}]}}
    creationTimestamp: null
    generation: 1
    labels:
      app: jenkins
      openshift.io/deployment-config.name: jenkins
    name: jenkins-1
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: jenkins
      uid: 16ff7684-695f-11e7-b631-026048c65d66
  spec:
    replicas: 1
    selector:
      app: jenkins
      deployment: jenkins-1
      deploymentconfig: jenkins
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: jenkins
          openshift.io/deployment.name: jenkins-1
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: jenkins
          deployment: jenkins-1
          deploymentconfig: jenkins
      spec:
        containers:
        - image: docker.io/library/jenkins@sha256:1a017bc762d8177347dbccbe258de842015114806110db060d91cff7e8a3264f
          imagePullPolicy: IfNotPresent
          name: jenkins
          ports:
          - containerPort: 50000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: jenkins-volume-1
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: jenkins
    name: jenkins
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 50000-tcp
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: jenkins
      deploymentconfig: jenkins
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/created-by: |
        {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicationController","namespace":"aaa","name":"jenkins-1","uid":"176218a4-695f-11e7-b631-026048c65d66","apiVersion":"v1","resourceVersion":"3644"}}
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: jenkins
      openshift.io/deployment.name: jenkins-1
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/scc: restricted
    creationTimestamp: null
    generateName: jenkins-1-
    labels:
      app: jenkins
      deployment: jenkins-1
      deploymentconfig: jenkins
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: jenkins-1
      uid: 176218a4-695f-11e7-b631-026048c65d66
  spec:
    containers:
    - image: docker.io/library/jenkins@sha256:1a017bc762d8177347dbccbe258de842015114806110db060d91cff7e8a3264f
      imagePullPolicy: IfNotPresent
      name: jenkins
      ports:
      - containerPort: 50000
        protocol: TCP
      - containerPort: 8080
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
          - SYS_CHROOT
        privileged: false
        runAsUser: 1000090000
        seLinuxOptions:
          level: s0:c10,c0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/jenkins_home
        name: jenkins-volume-1
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-gzrzf
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-0vgwk
    nodeName: ip-172-31-55-251.us-west-2.compute.internal
    nodeSelector:
      region: primary
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000090000
      seLinuxOptions:
        level: s0:c10,c0
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - emptyDir: {}
      name: jenkins-volume-1
    - name: default-token-gzrzf
      secret:
        defaultMode: 420
        secretName: default-token-gzrzf
  status:
    phase: Pending
    qosClass: BestEffort
