kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "jjb"
spec:
  template:
    metadata:
      labels:
        name: "jjb"
    spec:
      containers:
        - name: "jjb"
          image: "docker.io/hongkailiu/jjb:2.0.3"
  triggers:
    - type: "ConfigChange"
  replicas: 1
