kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "myapp"
spec:
  template: 
    metadata:
      labels:
        name: "myapp"
    spec:
      containers:
        - name: "helloworld"
          image: "docker.io/hongkailiu/ycsb:001"
  replicas: 1
  
