kind: Service
apiVersion: v1
metadata:
  name: fio-service
spec:
  selector:
    name: receiver
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 22
      nodePort: 32500
  type: NodePort