apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: docker.io/jenkins
      ports:
        - containerPort: 8080
      volumeMounts:
        - mountPath: /var/jenkins_home
          name: ddd
  volumes:
  - name: ddd
    persistentVolumeClaim:
      claimName: pvc-ebs
