apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: test-go
      image: quay.io/hongkailiu/test-go:http-0.0.10
      ports:
        - containerPort: 8080
