apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: docker.io/nginx
      ports:
        - containerPort: 80
      securityContext:
          privileged: true
      volumeMounts:
        - mountPath: /var/cache/nginx
          name: ddd
  volumes:
  - name: ddd
    persistentVolumeClaim:
      claimName: pvc-ebs
