kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "registry"
  annotations:
    volume.alpha.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "300Gi"

root@ip-172-31-20-63: ~ # cat registry_secret.yaml 
version: 0.1
log:
  level: debug
http:
  addr: :5000
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /registry
auth:
  openshift:
    realm: openshift
middleware:
  registry:
  - name: openshift
  repository:
  - name: openshift
    options:
      pullthrough: True
      acceptschema2: False
      enforcequota: False
  storage:
  - name: openshift

