kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "registry"
  annotations:
    volume.alpha.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "200Gi"
