### $ ansible-playbook -i "35.188.42.183,35.232.243.87,35.188.134.137," playbooks/copy_libra_key.yaml  --extra-vars "ansible_user=root ansible_ssh_private_key_file=/home/hongkliu/.ssh/libra.pem"
---
- hosts: all
  become: yes
  become_user: root
  vars:
    key_src: "/home/hongkliu/.ssh/libra.pem"

  tasks:
  - name: get home folder
    shell: echo ${HOME}
    register: home_result
  - name: show home folder
    debug:
      msg: "remote home is: {{ home_result.stdout }}"
  - name: copy the libra key
    copy:
      src: "{{ key_src }}"
      dest: "{{ home_result.stdout }}/.ssh/id_rsa"
      mode: 0600