---
- hosts: all
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /home/hongkliu/.ssh/id_rsa_perf
  tasks:
    - name: set result
      set_fact:
        result: "{{ not openshift_web_console_install | default(true) | bool }}"

    - name: show result
      debug:
        msg: "result: {{ result }}"