---

- name: Run oc get user redhat
  command: oc get user redhat -o yaml
  register: oc_get_user_redhat_result

- debug: msg="{{ oc_get_user_redhat_result.stdout }}"

- debug: msg="{{ oc_get_user_redhat_result.stderr }}"


- block:
  - name: Copy templates
    set_fact:
      nfs_service_ip: "unknown.yet"
  - name: Copy templates
    template: src="{{ item }}" dest="/tmp/{{ item | basename | regex_replace('\.j2','') }}"
    with_fileglob:
      - ../templates/*.j2
  - name: Create project svt-test-nfs
    command: "{{ item }}"
    with_items:
      - oc login -u redhat -p redhat
      - oc new-project {{ nfs_project_name }}
      - oc label namespace {{ nfs_project_name }} purpose=test
      - oc create -f /tmp/scc_super.yaml
      - oc label scc super-svt-test-nfs purpose=test
      - oc create -f /tmp/items_nfs-server.yaml
      - oc login -u system:admin
  - name: get nfs-service ip
    shell: oc get service nfs-service | grep nfs-service | awk '{print $2}'
    register: oc_get_service_nfs_service_result
  - name: Copy templates
    set_fact:
      nfs_service_ip: "{{ oc_get_service_nfs_service_result.stdout }}"
  - name: Copy template pv_nfs.yaml
    template:
      src: pv_nfs.yaml.j2
      dest: /tmp/pv_nfs.yaml
  when:
    - '"name: redhat" in oc_get_user_redhat_result.stdout'